#!/usr/bin/bash

filename='./file.txt'
n=1
while read line;
do
echo "Line no. $n : $line"
echo ${#line}
if [[ ${#line} -gt 5 ]]
then
echo "$line is ${#line} chars long"
fi
n=$((n + 1 ))
done < $filename
